### ISSUE TITLE
Mimicking losses confusion

### ISSUE THREAD

**Issue by Zhaoyi-Yan** [d-li14/DHM#1]
```
To stabilize the training process and avoid further regularization
effect, we fork auxiliary classifiers from each node of
the backbone network with probabilities toggling between
zero and one in our main experiments, following a binary
sampling strategy along the axis of network forward propagation.
```
I am not sure what these words means.  From the code https://github.com/d-li14/DHM/blob/master/imagenet.py#L326, it seems you just calculate all the combinations of mimicking losses.

**Comment by d-li14** [comment]
As stated by the paper, forking auxiliary branch or not at each node of the backbone is defined as a dynamic process. Here the nodes with auxiliary branches imply that we fork with the probability 1, while all the other nodes without branches with probability 0. This is the so-called binary (0-1) sampling. You could further try Bernoulli sampling with the probability of 0.5 in these existing branches with the commented lines https://github.com/d-li14/DHM/blob/master/imagenet.py#L334-L336.
